### Задание 
#### Написать функцию, которая находит самое часто встречающееся число в каждой строке матрицы и возвращает массив этих значений

### Импорт

In [1]:
from statistics import mode
import numpy as np

### Считаем моду в каждой строке

In [2]:
def f(x):
    modes = []
    for line in x:
        modes.append(mode(line))
    return modes

### Пример выполнения

In [3]:
m = np.random.randint(-4,4,size=(10,10))
print(m)
f(m)

[[-3  0 -1  3 -4  3 -1  3  3  0]
 [ 2  3  1 -2 -3 -3  2  0  0 -2]
 [-4  1  3 -4  0 -3  2 -2  3  3]
 [-4  2  0  3 -1  2 -3  0  0 -4]
 [-3  1  3  1 -4  3 -4  3 -2  1]
 [ 3 -2 -2  1 -3 -2  2 -2  0  0]
 [ 2 -3 -4 -1 -4 -4 -2  0  1 -3]
 [ 2 -1  2  0 -2 -2 -3 -1  3  3]
 [-1 -2  0 -1 -1  3  2 -4 -1 -2]
 [-3  3  1 -1 -1  1 -1 -2  1 -2]]


[3, 2, 3, 0, 1, -2, -4, 2, -1, 1]